# This is a makefile for 6 source files: chessServer.cpp function.cpp figure.cpp pawn.cpp bishop.cpp king.cpp knight.cpp queen.cpp rook.cpp

final:
	g++ -pthread chessServer.cpp function.cpp figure.cpp pawn.cpp bishop.cpp king.cpp knight.cpp queen.cpp rook.cpp -o final
